# Generated by Django 6.0.1 on 2026-03-02 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_account_options_remove_account_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savingaccount',
            options={'verbose_name': 'Saving Account', 'verbose_name_plural': 'Saving Accounts'},
        ),
    ]
